src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateTime = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture = null;

    #[ORM\Column(nullable: true)]
    private ?int $capacity = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $contact_email = null;

    #[ORM\Column(nullable: true)]
    private ?string $contact_number = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->dateTime;
    }

    public function setDateTime(\DateTimeInterface $dateTime): static
    {
        $this->dateTime = $dateTime;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(?int $capacity): static
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getContactEmail(): ?string
    {
        return $this->contact_email;
    }

    public function setContactEmail(?string $contact_email): static
    {
        $this->contact_email = $contact_email;

        return $this;
    }

    public function getContactNumber(): ?int
    {
        return $this->contact_number;
    }

    public function setContactNumber(?int $contact_number): static
    {
        $this->contact_number = $contact_number;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', null,  ['attr' => ['class' => 'form-control', 'placeholder' => 'Event name'],])
            ->add('description', null,  ['attr' => ['class' => 'form-control', 'placeholder' => 'decription'],])
            ->add('capacity', null,  ['attr' => ['class' => 'form-control', 'placeholder' => 'insert max capacity of people'],])
            ->add('contact_email', null,  ['attr' => ['class' => 'form-control', 'placeholder' => 'please insert valid email'],])
            ->add('contact_number', null,  ['attr' => ['class' => 'form-control', 'placeholder' => 'please insert valid contact number'],])
            ->add('address', null,  ['attr' => ['class' => 'form-control', 'placeholder' => 'please insert the Event location'],])
            ->add('url', null,  ['attr' => ['class' => 'form-control', 'placeholder' => 'Url for event if possible'],])
            ->add('type', ChoiceType::class, [
                'choices' => [
                    'Music' => 'music',
                    'Sport' => 'sport',
                    'Movie' => 'movie',
                    'Theater' => 'theater'
                ],
                'attr' => ['class' => 'form-control', 'placeholder' => 'Select event type']
            ])
            ->add('dateTime', null, [
                'widget' => 'single_text'
            ])


            ->add('picture', FileType::class, [
                'label' => 'Picture (jpg,png,jpeg file)', //picture:column name
                'attr' =>  ['class' => 'form-control'], // to style by bootstrap
                'mapped' => false,
                'required' => false,  //don't force to upload pic, if True you force the user to insert image
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => ['image/jpg', 'image/png', 'image/jpeg'],
                        'mimeTypesMessage' => 'Please upload a valid image',
                    ])
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use App\Service\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/event')]
class EventController extends AbstractController
{
    #[Route('/', name: 'app_event_index', methods: ['GET'])]
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_event_new', methods: ['GET', 'POST'])]
    public function new(Request $request, FileUploader $fileUploader, EntityManagerInterface $entityManager): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $picture = $form->get('picture')->getData(); //picture come> AnimalType.php 
            if ($picture) {
                $pictureName = $fileUploader->upload($picture);
                $event->setPicture($pictureName);
            } // entity>Animal.php is setPicture
            else {
                $event->setPicture("picture.jpg");
            } // default pic if user don't select pic 
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_show', methods: ['GET'])]
    public function show(Event $event): Response
    {
        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);
    }


    #[Route('/type/{eventType}', name: 'app_event_filter_by_type', methods: ['GET'])]
    public function filterByType(string $eventType, EventRepository $eventRepository): Response
    {
        // Fetch events from the repository based on the provided type
        $events = $eventRepository->findBy(['type' => $eventType]);

        return $this->render('event/index.html.twig', [
            'events' => $events,
        ]);
    }




    #[Route('/{id}/edit', name: 'app_event_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Event $event, EntityManagerInterface $entityManager, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $picture = $form->get('picture')->getData();
            if ($picture) {
                if ($event->getPicture() != 'picture.jpg') {
                    unlink($this->getParameter('pictures_directory') . '/' . $event->getPicture());
                }
                $pictureName = $fileUploader->upload($picture);
                $event->setPicture($pictureName);
            }
            $entityManager->flush();
            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }


    #[Route('/{id}', name: 'app_event_delete', methods: ['POST'])]
    public function delete(Request $request, Event $event, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $event->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($event);
            $entityManager->flush();
            if ($event->getPicture() != 'picture.jpg') // hat entity w hat menha picture if the user doesn't insert pic it will be the default picture so use unlink to delete it 
            {
                unlink($this->getParameter('pictures_directory') . '/' . $event->getPicture());
            }
        }

        return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/event/_delete_form.html.twig
<form
  method="post"
  action="{{ path('app_event_delete', { id: event.id }) }}"
  onsubmit="return confirm('Are you sure you want to delete this item?');"
>
  <input
    type="hidden"
    name="_token"
    value="{{ csrf_token('delete' ~ event.id) }}"
  />
  <button class="btn btn-danger">Delete</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Event{% endblock %}

{% block body %}
    <h1>Edit Event</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_event_index') }}">back to list</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}

templates/event/index.html.twig
{# event/index.html.twig #} {% extends 'base.html.twig' %} {% block title
%}Events{% endblock %} {% block body %}
<!-- Hero Section -->
<section
  class="hero-section vh-100 d-flex justify-content-center align-items-center"
>
  <div class="container" style="max-height: 300px; overflow: auto">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Welcome to our Events Page</h1>
        <p>Find various types of events happening around you.</p>
      </div>
    </div>
    <!-- Menu -->
    <div class="row justify-content-center">
      <div class="col-md-6 text-center">
        <div class="list-group">
          <a
            href="{{ path('app_event_index') }}"
            class="list-group-item list-group-item-action"
            >All Events</a
          >
          <a
            href="{{
              path('app_event_filter_by_type', { eventType: 'music' })
            }}"
            class="list-group-item list-group-item-action"
            >Music Events</a
          >
          <a
            href="{{ path('app_event_filter_by_type', { eventType: 'art' }) }}"
            class="list-group-item list-group-item-action"
            >Art Events</a
          >
          <a
            href="{{
              path('app_event_filter_by_type', { eventType: 'movie' })
            }}"
            class="list-group-item list-group-item-action"
            >Movies Events</a
          >
          <a
            href="{{
              path('app_event_filter_by_type', { eventType: 'sport' })
            }}"
            class="list-group-item list-group-item-action"
            >Sport Events</a
          >
          <a
            href="{{
              path('app_event_filter_by_type', { eventType: 'theater' })
            }}"
            class="list-group-item list-group-item-action"
            >Theater Events</a
          >
        </div>
      </div>
    </div>
  </div>
</section>

<div class="row row-cols-3 p-2">
  {% for event in events %}
  <div class="col event-item" data-type="{{ event.type }}">
    <div class="card" style="width: 18rem">
      <img
        src="{{ asset('uploads/' ~ event.picture) }}"
        class="card-img-top"
        alt="..."
      />
      <div class="card-body">
        <h5 class="card-title">{{ event.name }}</h5>
        <p class="card-text">
          Date Time:
          {{ event.dateTime ? event.dateTime|date('Y-m-d H:i:s') : '' }}
        </p>
        <p class="card-text">Event Type: {{ event.type }}</p>
        <p class="card-text">Event Address: {{ event.address }}</p>
        <a
          href="{{ path('app_event_show', { id: event.id }) }}"
          class="btn btn-primary"
          >Show</a
        >
        <a
          href="{{ path('app_event_edit', { id: event.id }) }}"
          class="btn btn-warning"
          >Edit</a
        >
      </div>
    </div>
  </div>
  {% else %}
  <p class="card-text">No records found</p>
  {% endfor %}
</div>

{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Event{% endblock %}

{% block body %}
    <h1>Create new Event</h1>

    {{ include('event/_form.html.twig') }}

    <a href="{{ path('app_event_index') }}">back to list</a>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %} {% block title %}Event{% endblock %} {% block
body %}
<h1>Event</h1>

<div class="container">
  <div class="card" style="width: 18rem">
    <div class="card-body">
      <img
        src="{{ asset('uploads/' ~ event.picture) }}"
        class="card-img-top"
        alt="..."
      />

      <h5 class="card-title">{{ event.name }}</h5>
      <p class="card-text">
        Date Time:
        {{ event.dateTime ? event.dateTime|date('Y-m-d H:i:s') : '' }}
      </p>
      <p class="card-text">Description: {{ event.description }}</p>
      <p class="card-text">Capacity: {{ event.capacity }}</p>
      <p class="card-text">Contact Email: {{ event.contactEmail }}</p>
      <p class="card-text">Contact Number: {{ event.contactNumber }}</p>
      <p class="card-text">Address: {{ event.address }}</p>
      <p class="card-text">Event URL: {{ event.url }}</p>
      <p class="card-text">Event Type: {{ event.type }}</p>
      <a href="{{ path('app_event_index') }}" class="btn btn-success"
        >Back to List</a
      >
      <a
        href="{{ path('app_event_edit', { id: event.id }) }}"
        class="btn btn-warning"
        >Edit</a
      >
      {{ include("event/_delete_form.html.twig") }}
    </div>
  </div>
</div>
{% endblock %}